name: action-1
on: [push]
jobs:
  start-and-stop:
    runs-on: ubuntu-latest
    env: # Set the secret as an input
      API_KEY: ${{ secrets.AG_CLIENT_SECRET }}
    steps: 
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
        # - run: npm install winston
        # - run: node index
        - run: node ./.github/scripts/check
        