name: action-1
on: [push]
jobs:
  start-and-stop:
    runs-on: ubuntu-latest
    steps:
      - name: Run a node program that uses an external service that requires an API Key
        with: # Set the secret as an input
          API_KEY: ${{ secrets.AG_CLIENT_SECRET }}
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install winston
      - run: node index
      - run: node ./.github/scripts/check